#kafka
spring:
  kafka:
    bootstrap-servers: node3:9092,node4:9092,node5:9092,node7:9092,node8:9092
    consumer:
      group-id: 0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

######################### itaojin ###########################
itaojin:
  hbase:
    master: node3:600000
  zookeeper:
    quorum: node4,node7,node8
    port: 2181
  hive:
    driver: org.apache.hive.jdbc.HiveDriver
    preUrl: jdbc:hive2://node4:10000/


######################### logging ###########################
logging:
  level:
    com.qc.itaojin.canalclient: DEBUG
  file: /root/canal-client/canal-client.log


