#kafka
spring:
  kafka:
    bootstrap-servers: node2:9092,node3:9092,node4:9092
    consumer:
      group-id: 0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

######################### itaojin ###########################
itaojin:
  hbase:
    # 如果指定了master，则按照非高可用HBase的形式创建连接，反之则按照HA形式创建
#    master: node2:600000
    # 默认为 /hbase
    parent: /hbase
  zookeeper:
    quorum: node2,node3,node4
    port: 2181
  hive:
    driver: org.apache.hive.jdbc.HiveDriver
    preUrl: jdbc:hive2://node3:10000/


######################### logging ###########################
logging:
  level:
    com.qc.itaojin.canalclient: DEBUG
  file: /usr/local/src/canal_client/logs/canal-client.log


