#kafka
spring:
  kafka:
    bootstrap-servers: node2:9092,node4:9092,node5:9092
    consumer:
      group-id: 0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

######################### logging ###########################
logging:
  level:
    com.qc.itaojin.canalclient: DEBUG
  file: /usr/local/src/canal_client/logs/canal-client.log

######################### itaojin ###########################
itaojin:
  hbase:
    # 如果指定了master，则按照非高可用HBase的形式创建连接，反之则按照HA形式创建
#    master: node2:600000
    # 默认为 /hbase
    parent: /hbase
  zookeeper:
    quorum: node2,node3,node4,node5,node6
    port: 2181
  hive:
    driver: org.apache.hive.jdbc.HiveDriver
    preUrl: jdbc:hive2://node3:10000/

  canal:
    # canal客户端向server抓取数据的数据
    batchSize: 1000

    # tjk
    tjkDestination: tjk
    # 监听表格正则
    tjkFilterRegex: .*\..*
    # 客户端向服务端拉取数据的时间间隔（毫秒）
    tjkRequestInterval: 500

    # ai
    aiDestination: ai
    aiFilterRegex: .*\..*
    aiRequestInterval: 500

    # 支付
    payDestination: pay
    payFilterRegex: .*\..*
    payRequestInterval: 10000

    # 工作台
    benchDestination: bench
    benchFilterRegex: .*\..*
    benchRequestInterval: 1000

  mysql:
    driver: com.mysql.jdbc.Driver

    # tjk
    # 缺省schema，程序自动拼接
    tjkUrl: jdbc:mysql://rm-bp127us7d36zxqm7v.mysql.rds.aliyuncs.com:3306/
    tjkUserName: tjk_read
    tjkPassword: tjk_only_read

    # ai
    # 缺省schema，程序自动拼接
    aiUrl: jdbc:mysql://rm-bp1fyiq5b4v8szo26o.mysql.rds.aliyuncs.com:3306/
    aiUserName: canal
    aiPassword: canal

    # 支付
    payUrl: jdbc:mysql://182.140.146.204:4406/
    payUserName: canal
    payPassword: canal

    # 工作台
    benchUrl: jdbc:mysql://120.55.114.70:3306/
    benchUserName: tjkread
    benchPassword: tjkReadOnly

    # 自身系统使用的数据库，必有
    bizUrl: jdbc:mysql://192.168.4.31:3306/tjk_bigdata
    bizUserName: test
    bizPassword: test




