#kafka
spring:
  kafka:
#    bootstrap-servers: 192.168.46.128:9092
#    bootstrap-servers: itaojin105:9092,itaojin106:9092
    bootstrap-servers: itaojin105:9092,itaojin106:9092
    consumer:
      group-id: 0
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      enable-auto-commit: true
      auto-commit-interval: 100
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      batch-size: 65536
      buffer-memory: 524288

######################### itaojin ###########################
itaojin:
  hbase:
    master: itaojin102:600000
  zookeeper:
    quorum: itaojin105,itaojin106,itaojin107
    port: 2181
  hive:
    driver: org.apache.hive.jdbc.HiveDriver
    preUrl: jdbc:hive2://itaojin106:10000/


######################### logging ###########################
logging:
  level:
    com.qc.itaojin.canalclient: DEBUG
  file: /root/canal-client.log


