############################  zookeeper ##############################
zookeeper:
  servers: itaojin105:2181,itaojin106:2181,itaojin107:2181
  # 与servers的区别是不带端口信息
  quorum: itaojin105,itaojin106,itaojin107
  port: 2181

############################  canal的配置 ##############################
canal:
  # canal客户端向server抓取数据的数据
  batch-size: 1000

  # instance
  tjk-destination: tjk
  # 监听表格正则
  # filter-regex: .*\\..*
  tjk-filter-regex: test\\..*
  # 客户端向服务端拉取数据的时间间隔（毫秒）
  tjk-request-interval: 1000

  # ai
  ai-destination: ai
  ai-filter-regex: .*\\..*
  ai-request-interval: 1000

  # 支付
  pay-destination: pay
  pay-filter-regex: .*\\..*
  pay-request-interval: 1000

  # 工作台
  bench-destination: bench
  bench-filter-regex: .*\\..*
  bench-request-interval: 1000

############################ 数据源 ##############################
mysql:
  driver: com.mysql.jdbc.Driver

  # tjk
  # 缺省schema，程序自动拼接
  tjk-url: jdbc:mysql://192.168.4.31:3306/
  tjk-user-name: test
  tjk-password: test

  # ai
  ai-url: jdbc:mysql://192.168.4.31:3306/
  ai-user-name: test
  ai-password: test

  # 支付
  pay-url: jdbc:mysql://192.168.4.31:3306/
  pay-user-name: test
  pay-password: test

  # 工作台
  bench-url: jdbc:mysql://192.168.4.31:3306/
  bench-user-name: test
  bench-password: test

############################ kafka ##############################
kafka:
  topic: hello

############################ hive ##############################
hive:
  driver: org.apache.hive.jdbc.HiveDriver
  # schema可以动态切换
  url: jdbc:hive2://itaojin106:10000/

############################ hbase ##############################
hbase:
  master: itaojin102:600000
